import os
from pathlib import Path
from typing import Dict, Any


class LLMController:
    """Controller for LLM-based robot task planning and execution."""

    def __init__(self, object_manager, robot_controller):
        """
        Initialize the LLM controller.

        Args:
            object_manager: ObjectManager instance for querying object positions
            robot_controller: RobotController instance for executing commands
        """
        self.object_manager = object_manager
        self.robot_controller = robot_controller

        # Load task description
        self.task_description = self._load_file('llm_task_init.txt')

    def _load_file(self, filename: str) -> str:
        """Load text file content from prompts folder."""
        filepath = Path(__file__).parent.parent / 'prompts' / filename
        with open(filepath, 'r') as f:
            return f.read().strip()

    def _find_latest_panorama(self, pattern: str = "panorama_*_initial_stabilized.png") -> str:
        """Find the most recent panorama image matching the pattern."""
        images_dir = Path(__file__).parent.parent / "images"
        if not images_dir.exists():
            raise FileNotFoundError(f"Images directory not found: {images_dir}")

        # Find all matching panorama files
        import glob
        matching_files = glob.glob(str(images_dir / pattern))

        if not matching_files:
            raise FileNotFoundError(f"No panorama images found matching pattern: {pattern}")

        # Sort by modification time and get the most recent
        latest_file = max(matching_files, key=os.path.getmtime)
        return latest_file

    def execute_plan(self, plan: Dict[str, Any]) -> None:
        """
        Execute a command plan generated by the LLM.

        Args:
            plan: Dictionary containing 'commands' list with action/parameter pairs
        """
        if 'commands' not in plan:
            raise ValueError("Plan must contain 'commands' key")

        commands = plan['commands']

        print(f"=== EXECUTE LLM PLAN START === Commands: {len(commands)}")

        # Display reasoning if present
        if 'reasoning' in plan:
            print(f"\n--- EXECUTION REASONING ---")
            print(plan['reasoning'])
            print(f"--- END EXECUTION REASONING ---\n")

        for i, command in enumerate(commands, 1):
            action = command.get('action')

            if action == 'pick_up':
                object_name = command.get('object')
                if not object_name:
                    raise ValueError(f"Command {i}: 'pick_up' requires 'object' parameter")

                print(f"\n--- Command {i}/{len(commands)}: pick_up('{object_name}') ---")
                self.robot_controller.pick_up(object_name)

            elif action == 'place':
                position = command.get('position')
                if not position or len(position) != 3:
                    raise ValueError(f"Command {i}: 'place' requires 'position' parameter as [x, y, z]")

                print(f"\n--- Command {i}/{len(commands)}: place({position}) ---")
                self.robot_controller.place(position)

            elif action == 'place_on':
                object_name = command.get('object')
                if not object_name:
                    raise ValueError(f"Command {i}: 'place_on' requires 'object' parameter")

                print(f"\n--- Command {i}/{len(commands)}: place_on('{object_name}') ---")
                self.robot_controller.place_on(object_name)

            else:
                raise ValueError(f"Command {i}: Unknown action '{action}'")

        print(f"=== EXECUTE LLM PLAN END ===")
